# Base image
FROM php:8.0-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    nginx \
    supervisor 

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# PHP configs
COPY ./zk8s/php/php.ini /usr/local/etc/php/php.ini

# Supervisord configs
RUN mkdir -p /var/log/supervisor
COPY /zk8s/my_supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Nginx configs
# COPY /zk8s/nginx/laravel-app.conf /etc/nginx/sites-available/default
COPY /zk8s/nginx/nginx.conf /etc/nginx/
RUN rm /etc/nginx/sites-enabled/default

# Set working directory
WORKDIR /var/www

# Copy project files
COPY . .

# Install dependencies
# RUN composer install 
# --no-scripts --no-autoloader --no-dev --ignore-platform-reqs && \
#     composer dump-autoload --no-scripts --no-dev --optimize && \
#     rm -rf /root/.composer

# # Permission
RUN chown -R www-data:www-data /var/www && \
    chmod -R 775 /var/www/storage /var/www/bootstrap/cache && \
    chmod -R 775 /var/www/storage/logs

ENTRYPOINT [ "zk8s/entrypoint.sh" ]
# CMD ["/usr/bin/supervisord"]
# CMD [ "supervisord", "-c", "/etc/supervisor.conf" ]