apiVersion: v1
kind: Service
metadata:
  name: laravel-app
spec:
  selector:
    app: laravel-app
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer

# apiVersion: v1
# kind: Service
# metadata:
#   name: laravel-app
# spec:
#   type: NodePort
#   selector:
#     app: laravel-app
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 80